from src.data.nba_client import stat_information as stat_info, get_context_factors
from src.analysis.realized_vol import find_sigma
from src.data.odds_client import american_to_implied, remove_vigorish
import numpy as np
from scipy.stats import nbinom


def monte_carlo_prob(stat_list, K, stat_category, n_simulations=10000, pace_factor=1.0, def_factor=1.0, bookmaker='DraftKings'):
    """
    Generate the distribution for a selected stat through specific distribution constraints and a Monte Carlo Simulation
    and the probability of Monte Carlo's suggested direction (over/under).

    Args: 
        stat_list: An array of up to 10 integers representing the player's most recent
                   qualifying game values for the selected stat, ordered most-recent-first (List).
        K: Value that represents the prop line for the chosen player and stat (Float).
        stat_category: The selected stat for the player prop (String).
        n_simulations: Initialized to 10000, the number of samples generated by the model (Integer).
        pace_factor: Initialized to 1, represents the estimated number of possessions the opponent team averages per 48 minutes
                     relative to the league average pace.(Float). 
                    < 1.0 means slower than the league average, > 1.0 means faster than the league average.
        def_factor: Initialized to 1, represents how tough the opponent's defense is compared to rest of the league (Float). 
                    < 1.0 is relatively good defensive team, > 1.0 is a relatively bad defensive team. 
        bookmaker: Initialized to DraftKings, affects the probability the Monte Carlo Simulation produces as sportsbook hit
                   requirements differ between sportsbooks and prediction markets (String).

    Returns:
        prob_over: The probability that the prop is correct based off of the Monte Carlo Simulated Distribution (Float)
        simulations_tolist(): The array of all simulated values of the specific prop stat that is later visualized in
                              the application (List).
    """
        
    stat_array = np.array(stat_list, dtype=float)
    mu_raw = np.mean(stat_array)
    sigma = np.std(stat_array)
    mu = mu_raw * pace_factor * def_factor

    # Short circuits probability if player has the same value for that stat across all previous 10 games.
    if sigma == 0:
        if bookmaker == 'Kalshi':
            return (1.0 if mu >= K else 0.0), np.full(n_simulations, mu).tolist()
        else:
            return (1.0 if mu > K else 0.0), np.full(n_simulations, mu).tolist()

    variance = sigma ** 2
    # Monte Carlo Simulation for either a Negative Binomial or Poisson Distribution.
    if stat_category in ['rebounds', 'assists', 'steals', 'blocks', 'threes', 'turnovers']:
        if variance > mu:
            r = (mu ** 2) / (variance - mu)
            p = mu / variance
            simulations = nbinom.rvs(r, p, size=n_simulations)
        else:
            simulations = np.random.poisson(mu, size=n_simulations)
    # Monte Carlo Simulation for either a Normal or Log-Normal Distribution
    else:
        cv = sigma / mu_raw if mu_raw > 0 else 1.0
        if cv < 0.5:
            simulations = np.random.normal(mu, sigma, n_simulations)
            simulations = np.clip(simulations, 0, None)
        else:
            simulations = np.random.lognormal(
                mean=np.log(mu ** 2 / np.sqrt(variance + mu ** 2)),
                sigma=np.sqrt(np.log(1 + variance / mu ** 2)),
                size=n_simulations
            )
    # Adjusts for the difference in what counts as a hit between sportsbooks and prediction markets
    if bookmaker == 'Kalshi':
        prob_over = float(np.sum(simulations >= K) / n_simulations)
    else:
        prob_over = float(np.sum(simulations > K) / n_simulations)

    return prob_over, simulations.tolist()
        
def get_true_prob(stat_list, K, bookmaker='DraftKings'):
    """
    Generate a weighted empirical probability that the selected player prop is correct in a specified direction (over/under).

    Args:
        stat_list: An array of up to 10 integers representing the player's most recent
                   qualifying game values for the selected stat, ordered most-recent-first (List).
        K: Value that represents the prop line for the chosen player and stat (Float).
        bookmaker: Initialized to DraftKings, affects the produced probability as sportsbook hit
                   requirements differ between sportsbooks and prediction markets (String).

    Returns:
            A float between 0.0 and 1.0 representing the recency-weighted probability that the player's stat 
            clears the prop line K. More recent games are weighted more heavily than older games in the window.
    """
    
    weights = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
    weighted_sum = 0
    total_weight = 0
    # Short circuit if there are no qualifying games for that player
    if len(stat_list) == 0:
        return 0.0
    for i in range(len(stat_list)):
        weight = weights[i]
        if bookmaker == 'Kalshi':
            if stat_list[i] >= K:
                weighted_sum += weight
        else:
            if stat_list[i] > K:
                weighted_sum += weight
        total_weight += weight
    return weighted_sum / total_weight

# Function originally named find_impliedvol because initial focus was to use Black-Scholes as a model for determining player props.
def find_impliedvol(player_name, season, stat_category, prop, player_team=None, opponent_team=None, bookmaker='DraftKings'):
    """
    Easiest understood as a function wrapper. Takes the last 10 qualifying games for that player and stat. Fetches league's PACE and DRTG.
    PACE factor and DEF factor get calculated through the call to get_context_factors(). Produces the Monte Carlo Simulations' probabilities
    alongside those of the weighted empirical probability method.

    Args:
        player_name: Name of the player (String).
        season: Name of the season in the format 20XX - YY that is passed into the NBA Stats API (String).
        stat_category: The selected stat for the player prop (String).
        player_team: Initialized to None. The team that the selected player is on (String).
        opponent_team: Initialized to None. The team that the selected player is playing against (String).
        bookmaker: Initialized to DraftKings, affects the produced probability as sportsbook hit
                   requirements differ between sportsbooks and prediction markets (String).

    Returns:
            mc_prob_over: Number between 0 and 1 representing the Monte Carlo probability of the over hitting (Float).
            mc_prob_under: Number between 0 and 1 representing the Monte Carlo probability of the under hitting (Float).
            empirical_prob_over: Number between 0 and 1 representing the Weighted Empirical probability of the over hitting (Float).
            empirical_prob_under: Number between 0 and 1 representing the Weighted Empirical probability of the under hitting (Float).
            fair_over: The market's probabiltiy of the over hitting with vig removed (Float).
            fair_under: The market's probability of the under hitting with vig removed (Float).
            realized_vol: Log Return Std. Dev. of the player's performance in that stat across the L10 qualified games (Float).
            S: The raw rolling average for the player in the selected stat without adjustment for PACE or DRTG (Float).
            K: Value that represents the prop line for the chosen player and stat (Float).
            simulations: List of the 10,000 simulated stat outcomes for the chosen player and stat (List).
    """
    
    stat_list = stat_info(player_name, season, stat_category)
    realized_vol = find_sigma(stat_list)
    S = sum(stat_list) / len(stat_list)
    K = prop['line']
    over_odds = prop['over_odds']
    under_odds = prop['under_odds']
    implied_over = american_to_implied(over_odds)
    implied_under = american_to_implied(under_odds)
    fair_over, fair_under = remove_vigorish(implied_over, implied_under)

    pace_factor = 1.0
    def_factor = 1.0

    if player_team and opponent_team:
        pace_factor, def_factor = get_context_factors(player_team, opponent_team, season, stat_category)

    mc_prob_over, simulations = monte_carlo_prob(stat_list, K, stat_category, pace_factor=pace_factor, def_factor=def_factor, bookmaker=bookmaker)
    mc_prob_under = 1 - mc_prob_over
    empirical_prob_over = get_true_prob(stat_list, K, bookmaker=bookmaker)
    empirical_prob_under = 1 - empirical_prob_over

    return mc_prob_over, mc_prob_under, empirical_prob_over, empirical_prob_under, fair_over, fair_under, realized_vol, S, K, simulations
